color0 #13202a
color1 #fd4663
color2 #67ade4
color3 #d6745c
color4 #9366cc
color5 #93c5ec
color6 #e9a696
color7 #f2f2f3
color8 #5f6b74
color9 #fd4663
color10 #67ade4
color11 #d6745c
color12 #9366cc
color13 #93c5ec
color14 #e9a696
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #13202a
background            #13202a
foreground            #f2f2f3
selection_foreground  #afb3b6
selection_background  #192b38
active_border_color   #67ade4
inactive_border_color #192b38
url_color             #67ade4

active_tab_foreground   #171d23
active_tab_background   #67ade4
inactive_tab_foreground #afb3b6
inactive_tab_background #192b38
cursor_trail_color      #afb3b6
