color0 #291414
color1 #bd5251
color2 #e46867
color3 #d69a5c
color4 #669dcc
color5 #ec9393
color6 #e9c096
color7 #f3f2f2
color8 #756161
color9 #bd5251
color10 #e46867
color11 #d69a5c
color12 #669dcc
color13 #ec9393
color14 #e9c096
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291414
background            #291414
foreground            #f3f2f2
selection_foreground  #b6afaf
selection_background  #371b1b
active_border_color   #e46867
inactive_border_color #371b1b
url_color             #e46867

active_tab_foreground   #251918
active_tab_background   #e46867
inactive_tab_foreground #b6afaf
inactive_tab_background #371b1b
cursor_trail_color      #b6afaf
