color0 #1b1924
color1 #fd4663
color2 #7b67e4
color3 #b05cd6
color4 #cc66bc
color5 #a193ec
color6 #cf96e9
color7 #f2f2f3
color8 #666479
color9 #fd4663
color10 #7b67e4
color11 #b05cd6
color12 #cc66bc
color13 #a193ec
color14 #cf96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1b1924
background            #1b1924
foreground            #f2f2f3
selection_foreground  #b0afb6
selection_background  #242230
active_border_color   #7b67e4
inactive_border_color #242230
url_color             #7b67e4

active_tab_foreground   #1a1825
active_tab_background   #7b67e4
inactive_tab_foreground #b0afb6
inactive_tab_background #242230
cursor_trail_color      #b0afb6
