font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
disable_ligatures never

window_padding_width 18
placement_strategy   center
background_opacity   0.98
dynamic_background_opacity yes
hide_window_decorations    yes
confirm_os_window_close    0

cursor_shape         beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.5
shell_integration    no-cursor
# background           #1a1b26
# foreground           #a9b1d6
# selection_background #283457
# selection_foreground #a9b1d6
# url_color            #73daca
# cursor               #c0caf5
# color0 #15161e
# color8 #414868
# color1 #f7768e
# color9 #f7768e
# color2 #9ece6a
# color10 #9ece6a


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME